const data = [
  {
    id: 1,
    title: 'Showreel',
    image: '/img-showreel.png',
    video: '/showreel.mp4',
    description: 'Premier Showreel de Nima',
    category: 'Showreel',
  },
  {
    id: 2,
    title: 'Docu 1',
    image: '/realisation-1.jpg',
    video: '/videos/realisation2.mp4',
    description: 'Description de la réalisation 2.',
    category: 'documentaire'
  },
  {
    id: 3,
    title: 'Clip 1',
    image: '/realisation-2.jpg',
    video: '/videos/realisation3.mp4',
    description: 'Description de la réalisation 3.',
    category: 'clip'
  },
  {
    id: 4,
    title: 'Docu 2',
    image: '/realisation-3.jpg',
    video: '/videos/realisation4.mp4',
    description: 'Description de la réalisation 4.',
    category: 'documentaire'
  },
  {
    id: 5,
    title: 'Docu 3',
    image: '/realisation-1.jpg',
    video: '/videos/realisation5.mp4',
    description: 'Description de la réalisation 5.',
    category: 'documentaire',
  },
  {
    id: 6,
    title: 'Clip 2',
    image: '/realisation-2.jpg',
    video: '/videos/realisation6.mp4',
    description: 'Description de la réalisation 6.',
    category: 'clip',
  },
  {
    id: 7,
    title: 'Docu 4',
    image: '/realisation-3.jpg',
    video: '/videos/realisation7.mp4',
    description: 'Description de la réalisation 7.',
    category: 'documentaire',
  },
  {
    id: 8,
    title: 'Clip 3',
    image: '/realisation-1.jpg',
    video: '/videos/realisation8.mp4',
    description: 'Description de la réalisation 8.',
    category: 'clip'
  },
  {
    id: 9,
    title: 'Test 2.1',
    image: '/realisation-2.jpg',
    video: '/videos/realisation9.mp4',
    description: 'Description de la réalisation 9.',
    category: 'test2',
  },
  {
    id: 10,
    title: 'Mariage 1',
    image: '/realisation-3.jpg',
    video: '/videos/realisation10.mp4',
    description: 'Description de la réalisation 10.',
    category: 'mariage'
  },
  {
    id: 11,
    title: 'Clip 4',
    image: '/realisation-1.jpg',
    video: '/videos/realisation11.mp4',
    description: 'Description de la réalisation 11.',
    category: 'clip'
  },
  {
    id: 12,
    title: 'Mariage 2',
    image: '/realisation-2.jpg',
    video: '/videos/realisation12.mp4',
    description: 'Description de la réalisation 12.',
    category: 'mariage'
  },
  {
    id: 13,
    title: 'Test 1.1',
    image: '/realisation-2.jpg',
    video: '/videos/realisation9.mp4',
    description: 'Description de la réalisation 9.',
    category: 'test',
  },
  {
    id: 14,
    title: 'Clip 5',
    image: '/realisation-3.jpg',
    video: '/videos/realisation10.mp4',
    description: 'Description de la réalisation 10.',
    category: 'clip',
  },
  {
    id: 15,
    title: 'Test 1.2',
    image: '/realisation-1.jpg',
    video: '/videos/realisation11.mp4',
    description: 'Description de la réalisation 11.',
    category: 'test',
  },
  {
    id: 16,
    title: 'Clip 6',
    image: '/realisation-2.jpg',
    video: '/videos/realisation12.mp4',
    description: 'Description de la réalisation 12.',
    category: 'clip',
  },
  {
    id: 17,
    title: 'Docu 5',
    image: '/realisation-3.jpg',
    video: '/videos/realisation13.mp4',
    description: 'Description de la réalisation 13.',
    category: 'documentaire',
  },
  {
    id: 18,
    title: 'Docu 6',
    image: '/realisation-2.jpg',
    video: '/videos/realisation14.mp4',
    description: 'Description de la réalisation 14.',
    category: 'documentaire',
  },
  {
    id: 19,
    title: 'Docu 7',
    image: '/realisation-1.jpg',
    video: '/videos/realisation15.mp4',
    description: 'Description de la réalisation 15.',
    category: 'documentaire',
  },
  {
    id: 20,
    title: 'Docu 8',
    image: '/realisation-3.jpg',
    video: '/videos/realisation16.mp4',
    description: 'Description de la réalisation 16.',
    category: 'documentaire',
  },
  {
    id: 21,
    title: 'Docu 9',
    image: '/realisation-1.jpg',
    video: '/videos/realisation17.mp4',
    description: 'Description de la réalisation 17.',
    category: 'documentaire',
  },
  {
    id: 22,
    title: 'Docu 10',
    image: '/realisation-3.jpg',
    video: '/videos/realisation18.mp4',
    description: 'Description de la réalisation 18.',
    category: 'documentaire',
  },
  {
    id: 23,
    title: 'Docu 11',
    image: '/realisation-2.jpg',
    video: '/videos/realisation19.mp4',
    description: 'Description de la réalisation 19.',
    category: 'documentaire',
  },
  {
    id: 24,
    title: 'Docu 12',
    image: '/realisation-1.jpg',
    video: '/videos/realisation20.mp4',
    description: 'Description de la réalisation 20.',
    category: 'documentaire',
  }
];

export default data;
